# Generated by Django 4.0.6 on 2024-12-02 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCard',
            fields=[
                ('card_no', models.IntegerField(primary_key=True, serialize=False)),
                ('card_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('img_link', models.URLField(unique=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template Card',
                'verbose_name_plural': 'Template Cards',
                'db_table': 'templateCard',
            },
        ),
        migrations.CreateModel(
            name='GeneratedCard',
            fields=[
                ('gen_no', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('gen_img_link', models.URLField(unique=True)),
                ('gen_date', models.DateTimeField(auto_now_add=True)),
                ('card_no', models.ForeignKey(db_column='cardNo', on_delete=django.db.models.deletion.CASCADE, to='polls.templatecard')),
            ],
            options={
                'verbose_name': 'Generated Card',
                'verbose_name_plural': 'Generated Cards',
                'db_table': 'generatedCard',
            },
        ),
    ]
