# Generated by Django 4.0.6 on 2024-12-30 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCard',
            fields=[
                ('cardNo', models.IntegerField(primary_key=True, serialize=False)),
                ('cardName', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=10)),
                ('imgLink', models.URLField(unique=True)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template Card',
                'verbose_name_plural': 'Template Cards',
                'db_table': 'templateCard',
            },
        ),
        migrations.CreateModel(
            name='GeneratedCard',
            fields=[
                ('genNo', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('genImgLink', models.ImageField(blank=True, null=True, upload_to='')),
                ('text1', models.CharField(default='', max_length=20)),
                ('text2', models.CharField(default='', max_length=20)),
                ('genDate', models.DateTimeField(auto_now_add=True)),
                ('cardNo', models.ForeignKey(db_column='cardNo', on_delete=django.db.models.deletion.CASCADE, to='polls.templatecard')),
            ],
            options={
                'verbose_name': 'Generated Card',
                'verbose_name_plural': 'Generated Cards',
                'db_table': 'generatedCard',
            },
        ),
    ]
