# Generated by Django 4.0.6 on 2024-12-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedcard',
            name='category',
        ),
        migrations.AddField(
            model_name='generatedcard',
            name='cardName',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
